### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by jaygray0919** [lszeremeta/MEgen#1]
Would you post sample data that hydrates https://megen.top/

Previousl we had this item: https://megen.ga/7490245013/DS5_PubChem_Covid19_microdata_50_molecules.html

But it's no longer active.

we are testing your generated JSON-LD on an implemetation of Gregg Kellogg's SDL.

after we generate SDL results we'll share back on this thread

**Comment by lszeremeta** [comment]
Sure, sample data generated by MEgen is now available as a [dataset on Mendeley Data](https://data.mendeley.com/datasets/n9xwfs5fcj/1) (DS5 - bigger dataset, DS5s - set of 10 files with one molecule each). You can read more in the README.txt and dataset description.

**Comment by jaygray0919** [comment]
Here's one file:
https://klpuiljexh.execute-api.us-east-1.amazonaws.com/Prod/?url=https:%2F%2Fafdsi.com%2Fmegen%2Fmain%2FDS5_PubChem_Covid19_Microdata.html

several others fail, and we're not sure why. but the problem is on our side, not yours.
but now we have some god samples for testing.

**Comment by lszeremeta** [comment]
Thanks for test it :+1:

**Comment by jaygray0919** [comment]
we're getting a better handle on this now.
we have two flavors of SDL on AWS:
- SDL/Lambda
- SDL/EC2

we configure SDL/EC2 as-needed; it's expensive to keep online (it uses the largest AWS CPU for this workload)
we set up a spot server and run big jobs on weekends so we don't get booted before completion
SDL/EC2 could easily process DS1_ChEBI_complete.jsonld (it might take a couple of hours)
we have SDL/EC2 jobs that ran for three days (and worked!)

then there is SDL/Lambda
this configuration in mercurial
we previously processed files larger than 500 KB but now are running into problems with DS3_Wikidata_RDFa.html (309 KB)
our thinking is that AWS has either allocated a lower power processor to our Lambda server or has changed its job duration rules

we're working with GreggK and others to provide a complement to Google SDTT
the goal is to cover the expense of keeping SDL/EC2 online
let me know if you are interested, or know others who might be interested

but i will continue to fund the SDL/Lambda version and negotiate with AWS on parameters

/jay

**Comment by lszeremeta** [comment]
Yeah, DS1 is based on the largest possible ChEBI dataset type (so-called complete) with over 120,000 molecules. Nice that the datasets were useful. Thank you for detailed summary and I keep my fingers crossed :muscle:
